services:
    login-api:
      image: maven:3.8.5-openjdk-17
      volumes:
          - ./api:/usr/src
      networks:
          - login-networks
      working_dir: /usr/src
      command: bash -c "mvn clean package && java -jar ./target/login-0.0.1-SNAPSHOT.jar"
      tty: true
      depends_on:
        - keycloak
    login-app:
      build:
          context: ./
          dockerfile: Dockerfile.app
      volumes:
          - './app:/var/www/html'
      networks:
          - login-networks
      depends_on:
          - login-api
      working_dir: /var/www/html
      command: bash -c "composer install && npm install && php artisan serve --host=0.0.0.0 --port=8000"
    proxy:
      build: ./nginx
      volumes: 
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        - ./nginx/index.html:/usr/share/nginx/html/index.html
        - ./nginx/index.html:/usr/share/nginx/html/welcome/index.html
      ports:
        - 80:80
      depends_on:
        - login-app
      networks:
          - login-networks
    keycloak:
      image: quay.io/keycloak/keycloak:26.0.5
      volumes:
        - ./keycloak:/opt/keycloak/data/import
      environment:
        - KC_BOOTSTRAP_ADMIN_USERNAME=admin
        - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      command: start-dev --import-realm --hostname http://auth.localhost:8080 --hostname-backchannel-dynamic true
      ports:
        - 8080:8080
      networks:
          - login-networks
networks:
    login-networks:
        driver: bridge
