version: '3'
services:
    login-api:
      image: maven:3.8.5-openjdk-17
      volumes:
          - ./api:/usr/src
      networks:
          - login-networks
      working_dir: /usr/src
      command: bash -c "mvn clean package && java -jar ./target/login-0.0.1-SNAPSHOT.jar"
      tty: true
      depends_on:
        - login-keycloak
    login-app:
      build:
          context: ./
          dockerfile: Dockerfile.app
      volumes:
          - './app:/var/www/html'
      networks:
          - login-networks
      depends_on:
          - login-api
      working_dir: /var/www/html
      command: bash -c "composer install && npm install && php artisan serve --host=0.0.0.0 --port=8000"
      ports:
        - 80:8000
    login-keycloak:
      image: quay.io/keycloak/keycloak
      volumes:
        - ./keycloak:/opt/keycloak/data/import
      environment:
        - KEYCLOAK_ADMIN=admin
        - KEYCLOAK_ADMIN_PASSWORD=admin
      command: start-dev
      ports:
        - 8080:8080
      networks:
          - login-networks
networks:
    login-networks:
        driver: bridge
